### ISSUE TITLE
Change WebSite Name :master 🇮🇳 

### ISSUE THREAD

**Issue by iamapurba2003** [The-Tech-Firm/Web-Dev-Projects#3]
Update the Name of the Website to "The Tech Firm" ... Where it has Origin or CODEGEN written 

# Works to do
- [x] Received the issue 
- [x] Working on it
- [x] Fixed Changes 
- [ ] Closing it ... Please give Approvals

**Comment by iamapurba2003** [comment]
@himangshuishere ... I have Opened the issue ... Did you receive it ... Also don't forget to change the Remote Repo Refs!

**Comment by himangshuishere** [comment]
Yeah I have received this issue and will keep in mind while working with it...

**Comment by iamapurba2003** [comment]
Yes, be careful while you change the website code ... Although you will be developing in another branch, still be careful about the changes you make ... So that it does not lead to Merge Conflicts with Master 

Also, dont forget to update the Remote Refs ...
@himangshuishere @TheArUnOdAyA

**Comment by iamapurba2003** [comment]
> Yeah I have received this issue and will keep in mind while working with it...

Yes, be careful while you change the website code ... Although you will be developing in another branch, still be careful about the changes you make ... So that it does not lead to Merge Conflicts with Master

Also, dont forget to update the Remote Refs ...
@himangshuishere @TheArUnOdAyA

**Comment by himangshuishere** [comment]
Added a commit in The-Tech-Firm-HD/01 branch and tagged the latest commit with tag [TTF-WDP-HD01](https://github.com/The-Tech-Firm/Web-Dev-Projects/releases/tag/TTF-WDP-HD01)

@himangshuishere

**Comment by himangshuishere** [comment]
This is a test comment from GitHub mobile
@himangshuishere

**Comment by iamapurba2003** [comment]
Hiii ... Test Comment

**Comment by iamapurba2003** [comment]
Hey there

**Comment by himangshuishere** [comment]
This is a test comment

**Comment by himangshuishere** [comment]
This is a test comment from Lenovo tab GitHub app

**Comment by iamapurba2003** [comment]
Test it out

**Comment by himangshuishere** [comment]
A test comment

**Comment by himangshuishere** [comment]
test cmnt

**Comment by himangshuishere** [comment]
test comment

**Comment by himangshuishere** [comment]
test comment for @iamapurba2003

**Comment by iamapurba2003** [comment]
@himangshuishere Change all the other names of CODEGEN/ORIGIN to THE TECH FIRM ... in the branch you just pushed (marked as ACTIVE)

**Comment by iamapurba2003** [comment]
@himangshuishere Change all the other names of CODEGEN/ORIGIN to THE TECH FIRM ... in the branch you just pushed (marked as ACTIVE)

**Comment by iamapurba2003** [comment]
> test comment
> 

@himangshuishere Please delete this Comment ... ASAP

**Comment by himangshuishere** [comment]
@iamapurba2003

**Comment by iamapurba2003** [comment]
> @iamapurba2003 

Delete this Comment @himangshuishere

**Comment by iamapurba2003** [comment]
# Please find the list of Changes to make on GitHub Repo **THE-TECH-FIRM**. 
- [ ] ON Portfolio Section under _follow us on GitHub_ embedd 4 li tags in which our GitHub Profile links & Organization link will be listed 

- [ ] On Team Section the last tab contains the name **_Origin Team_**. Change the name to **_The Tech Firm_**.

- [ ] Under **_Pricing Section_** **_Buisness Plan & Developer Plan_** contains dummy Text ... List out some meaningful text there which represents it like a Actual Website selling Services 

- [ ] Under **_Contact_** Section there is a tab containing Map. Change the _Location_, _Email_, _Contact Number ... To actual details.

- [ ] The section above the **_FOOTER_** contains the name **_ORIGIN_**. Change it to **_The Tech Firm_** ... 

- [ ] In the **_FOOTER_** section change the Rights to **_©THE TECH FIRM_**

PLEASE, mark the following changes & do it ASAP ... 
# IF any further queries ... Ask it ANYTIME

@himangshuishere  YOUR ATTENTION IS NEEDED ...

**Comment by iamapurba2003** [comment]
> # Please find the list of Changes to make on GitHub Repo **THE-TECH-FIRM/Web-Dev-Projects**. 
> - [ ] ON Portfolio Section under _follow us on GitHub_ embedd 4 li tags in which our GitHub Profile links & Organization link will be listed 
> 
> - [ ] On Team Section the last tab contains the name **_Origin Team_**. Change the name to **_The Tech Firm_**.
> 
> - [ ] Under **_Pricing Section_** **_Buisness Plan & Developer Plan_** contains dummy Text ... List out some meaningful text there which represents it like a Actual Website selling Services.
> 
> - [ ] Under **_Contact_** Section there is a tab containing Map. Change the _Location_, _Email_, _Contact Number_ ... To actual details.
> 
> - [ ] The section above the **_FOOTER_** contains the name **_ORIGIN_**. Change it to **_The Tech Firm** ... 
> 
> - [ ] In the **_FOOTER_** section change the Rights to **_©THE TECH FIRM_**.
> 
> PLEASE, mark the following changes & do it ASAP ... 
> # IF any further queries ... Ask it ANYTIME.
> 
> @himangshuishere  @TheArUnOdAyA YOUR ATTENTION IS NEEDED ... 
> 
> As you progress with each task Tick it out to **_Mark the Progress_**.
> 
> Review of changes will be done on the [CODEGEN](https://code.gen.in)

Guys I have not got any reply ... Reassigning the task to @himangshuishere @TheArUnOdAyA ... Revert back once seen 

Assigned by ~ 
@iamapurba2003

**Comment by TheArUnOdAyA** [comment]
Task received 
I am on it 
@iamapurba2003 
Changes will be reflected very soon
on the [WEBSITE](https://code.gen.in).

**Comment by iamapurba2003** [comment]
Thank You @TheArUnOdAyA for your urgent help & urgent Attention. The Work has been really fast for you ... Thank You @himangshuishere for your initial Conrtribution ... It was a great Team Work guys ... Thanks for your Co-operation ... 
Guys.

**Comment by TheArUnOdAyA** [comment]
Thankyou for letting me doing the work . It was a great experience working in such a real-life project 
. Hope to work more in this type of project  in near future. Thankyou. Author ~@iamapurba2003 Contributor ~@himangshuishere .

**Comment by iamapurba2003** [comment]
My Pleasure ... I am Closing the Issue Guys, the work is Really Appreciated ... 
Issue **_Change WebSite Name :master :india:  #3_**  will be closed now as the Work is done ...

# Issue Details ~ Final (Before Closing)

**_Dated_** ~ 18/08/21 Time ~ 1:29 PM
**_Issuer_** ~ Apurba Ghosh @iamapurba2003 
**_Author_** ~ Apurba Ghosh @iamapurba2003 
**_Contributors_** ~ **Arunodaya Biswas** @TheArUnOdAyA, **Himangshu De** @himangshuishere
